# -*- coding: utf-8 -*-
"""Explore page retained because it exists in the uploaded source of truth."""

JAVASCRIPT = r'''/* ───── Explore ───── */
function exploreQueryText(){const a=`(around:2000,${userLocation.lat},${userLocation.lon})`,q={attractions:`nwr["tourism"~"attraction|museum|viewpoint|gallery"]${a};nwr["historic"]${a};`,convenience:`nwr["shop"="convenience"]${a};`,toilets:`nwr["amenity"="toilets"]${a};`,coffee:`nwr["amenity"="cafe"]${a};`,pharmacy:`nwr["amenity"="pharmacy"]${a};`,shopping:`nwr["shop"~"mall|department_store"]${a};`,hotels:`nwr["tourism"~"hotel|guest_house"]${a};`,food:`nwr["amenity"~"restaurant|fast_food|food_court"]${a};`}[exploreCategory];return`[out:json][timeout:20];(${q});out center tags;`}
async function loadExplorePois(force=false){if(!userLocation)return;exploreLoading=true;exploreError='';renderExplore(false);const key=`chengduPoi:map:${locCache()}:${exploreCategory}`;if(force)store.set(key,'');try{const r=await fetchOverpass(exploreQueryText(),key);explorePois=normalizePois(r.data,'map').filter(p=>p.distance<=2000).slice(0,80);exploreError=r.cached?'cached':''}catch(e){explorePois=[];exploreError='failed'}exploreLoading=false;renderExplore(false)}
function selectExploreCategory(k){exploreCategory=k;selectedExplore=null;userLocation?loadExplorePois():renderExplore(false)}
function mapIcon(){return{attractions:'⌂',convenience:'▣',toilets:'●',coffee:'☕',pharmacy:'✚',shopping:'◇',hotels:'⌂',food:'●'}[exploreCategory]||'●'}
function renderExplore(fetchIfNeeded=true){
  if(map){try{map.remove()}catch(e){}map=null}poiMarkers=[];
  $('#explore').className='page app-page'+(currentPage==='explore'?' active':'');
  $('#explore').innerHTML=`<div class="app-head"><div><h1>${L('explore_title')}</h1><p>${L('explore_sub')}</p></div></div><div class="map-cats">${EXPLORE_CATS.map(k=>`<button class="map-cat ${k===exploreCategory?'active':''}" onclick="selectExploreCategory('${k}')">${icon(k==='attractions'?'landmark':k==='toilets'?'toilet':k==='pharmacy'?'pharmacy':k==='hotels'?'hotel':k==='food'?'food':k==='coffee'?'coffee':'shopping')} ${L(k==='shopping'?'shopping_places':k)}</button>`).join('')}</div>
  ${!userLocation?locationState('explore'):`<div class="real-map"><div id="mapCanvas"></div><div class="map-toolbar"><div class="map-note">${exploreLoading?L('nearby_loading'):exploreError?L(exploreError==='cached'?'cached':'service_down'):`${distanceText(userLocation.accuracy||0)} · ${L(exploreCategory==='shopping'?'shopping_places':exploreCategory)}`}</div><button class="map-control" onclick="recenterMap()" aria-label="${L('recenter')}">${icon('locate')}</button></div></div><div id="mapFallback" class="map-fallback-list">${exploreError==='failed'?`<div class="local-note"><a class="mini-btn" target="_blank" rel="noopener" href="${amapNearbyUrl(exploreCategory)}">${L('amap_nearby')}</a></div>`:''}${explorePois.slice(0,12).map(p=>poiRow(p)).join('')}</div>`}`;
  if(userLocation)setTimeout(initMap,40);
  if(userLocation&&fetchIfNeeded&&!exploreLoading&&!explorePois.length)setTimeout(()=>loadExplorePois(),80);
}
function initMap(){const el=$('#mapCanvas');if(!el||!userLocation)return;const amap=`<a class="mini-btn" target="_blank" rel="noopener" href="${amapNearbyUrl(exploreCategory)}">${L('amap_nearby')}</a>`;if(!globalThis.maplibregl){const f=$('#mapFallback');if(f)f.insertAdjacentHTML('afterbegin',`<div class="local-note">${L('map_unavailable')} ${L('map_list')} ${amap}</div>`);return}try{map=new maplibregl.Map({container:'mapCanvas',style:'https://tiles.openfreemap.org/styles/liberty',center:selectedExplore?[selectedExplore.lon,selectedExplore.lat]:[userLocation.lon,userLocation.lat],zoom:selectedExplore?16:14,attributionControl:true,localIdeographFontFamily:'Noto Sans SC, sans-serif'});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');const ue=document.createElement('div');ue.className='user-marker';userMapMarker=new maplibregl.Marker({element:ue}).setLngLat([userLocation.lon,userLocation.lat]).addTo(map);map.on('load',()=>{drawPoiMarkers();if(selectedExplore)openExploreSheet(selectedExplore.id)})}catch(e){const f=$('#mapFallback');if(f)f.insertAdjacentHTML('afterbegin',`<div class="local-note">${L('map_unavailable')} ${L('map_list')} ${amap}</div>`)}}
function drawPoiMarkers(){if(!map)return;poiMarkers.forEach(m=>m.remove());poiMarkers=explorePois.map(p=>{const el=document.createElement('div');el.className='poi-marker';el.innerHTML=`<span>${mapIcon()}</span>`;el.addEventListener('click',()=>openExploreSheet(p.id));return new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([p.lon,p.lat]).addTo(map)})}
function recenterMap(){if(map&&userLocation)map.flyTo({center:[userLocation.lon,userLocation.lat],zoom:15})}
function poiRow(p){return`<div class="poi-row paper-card" onclick="openExploreSheet('${esc(p.id)}')"><div><b>${esc(p.name)}</b><small>${distanceText(p.distance)} · ${L('walk',{n:p.walk})}</small></div><span>›</span></div>`}
function openExploreSheet(id){const p=explorePois.find(x=>x.id===id)||selectedExplore;if(!p)return;selectedExplore=p;if(map)map.flyTo({center:[p.lon,p.lat],zoom:16});const foodAction=exploreCategory==='food'?`<button onclick="openInFood('${esc(p.id)}')">${L('open_food')}</button>`:'';showModal(`<div class="sheet-title"><div><h2>${esc(p.name)}</h2><p>${distanceText(p.distance)} · ${L('walk',{n:p.walk})}</p></div><button class="sheet-close" onclick="closeModal()">×</button></div><div class="sheet-actions"><a class="main" target="_blank" rel="noopener" href="${amapNavigationUrl(p)}">${L('navigate')} →</a>${foodAction}</div>`)}
function focusExplore(id){const p=foodPois.find(x=>x.id===id);if(!p)return;selectedExplore=p;exploreCategory='food';explorePois=[p];closeModal();showPage('explore');setTimeout(()=>openExploreSheet(p.id),260)}
function openInFood(id){const p=explorePois.find(x=>x.id===id);if(!p)return;foodCategory='all';foodPois=[p];selectedFood=p;closeModal();showPage('food');setTimeout(()=>openFoodSheet(p.id),160)}

'''
